;; -*- lexical-binding: t; -*-
(deftheme nwine
  "Created 2026-01-31.")

(custom-theme-set-faces
 'nwine
 '(cursor ((t (:background "#cecece"))))
 '(escape-glyph ((t (:foreground "#46D9FF"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#8a8a8a" :background "#242424"))))
 '(highlight ((t (:foreground "black" :background "#7b8790"))))
 '(completions-common-part ((t (:foreground "darkred"))))
 '(completions-annotations ((t (:foreground "grey"))))
 '(region ((t (:extend t :foreground "black" :background "#87a0b0"))))
 '(shadow ((t (:foreground "#8a8a8a"))))
 '(secondary-selection ((t (:extend t :background "#686868"))))
 '(trailing-whitespace ((t (:background "#f8b0b0"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t (:foreground "#8a8a8a"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#686868"))))
 '(font-lock-constant-face ((t (:foreground "#9a9a9a"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:foreground "#8a8a8a" :inherit (font-lock-comment-face)))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:slant normal :foreground "#83a598" :inherit (font-lock-function-name-face)))))
 '(font-lock-function-name-face ((t (:weight bold :foreground "#83a598" :background "black"))))
 '(font-lock-keyword-face ((t (:foreground "#8ec07c"))))
 '(font-lock-negation-char-face ((t (:foreground "#8a8a8a" :inherit (bold)))))
 '(font-lock-number-face ((t (:foreground "#d3869b"))))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t (:foreground "#8a8a8a"))))
 '(font-lock-preprocessor-face ((t (:foreground "#8a8a8a" :inherit (bold)))))
 '(font-lock-property-name-face ((t (:weight normal :foreground "#b5ce9a" :background "black"))))
 '(font-lock-property-use-face ((t (:weight regular :inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t (:foreground "#d7ceb9"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#8a8a8a" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#8a8a8a" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#acacac"))))
 '(font-lock-type-face ((t (:foreground "#fabd2f"))))
 '(font-lock-variable-name-face ((t (:foreground "#f1e5c9"))))
 '(font-lock-variable-use-face ((t (:foreground "#f1e5c9" :inherit (font-lock-variable-name-face)))))
 '(font-lock-warning-face ((t (:inherit (warning)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight normal :foreground "#87afff"))))
 '(link-visited ((t (:inherit (link)))))
 '(fringe ((t (:foreground "#686868" :inherit (default)))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((t (:foreground "#f1e5c9" :background "black"))))
 '(mode-line ((t (:foreground "#f1e5c9" :background "black"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold :foreground "#f1e5c9"))))
 '(mode-line-highlight ((t (:weight bold :foreground "#f1e5c9"))))
 '(mode-line-inactive ((t (:foreground "#8a8a8a"))))
 '(isearch ((t (:weight bold :inherit (lazy-highlight)))))
 '(isearch-fail ((t (:weight bold :foreground "black" :background "#f8b0b0"))))
 '(lazy-highlight ((t (:weight bold :foreground "#efefef" :background "#5e7ab2"))))
 '(match ((t (:weight bold :foreground "#448844" :background "black"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'nwine)
